get:
  tags:
    - Product Return
  operationId: getAllProductReturns
  parameters:
    - name: page
      in: query
      required: false
      schema:
        type: integer
        format: int32
        default: 0
    - name: size
      in: query
      required: false
      schema:
        type: integer
        format: int32
        default: 10
  responses:
    "200":
      description: OK
      content:
        application/hal+json:
          schema:
            allOf:
              - $ref: "../../components/responses/v1/PaginatedResponseDTO.yaml"
              - type: object
                properties:
                  dataPage:
                    type: array
                    items:
                      $ref: "../../components/schemas/v1//response/ProductReturnResponseDTO.yaml"

post:
  tags:
    - Product Return
  operationId: addProductReturn
  requestBody:
    content:
      application/json:
        schema:
          $ref: "../../components/schemas/v1//request/ProductReturnRequestDTO.yaml"
    required: true
  responses:
    "201":
      description: Created
      content:
        application/hal+json:
          schema:
            allOf:
              - $ref: "../../components/responses/v1/ResponseDTO.yaml"
              - type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: "../../components/schemas/v1//response/ProductReturnResponseDTO.yaml"
    "400":
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: "../../components/responses/Problem.yaml"
    "409":
      description: Conflict
      content:
        application/json:
          schema:
            $ref: "../../components/responses/Problem.yaml"